### ISSUE TITLE
Default detections folder core24_model_based_unseen got updated, unable to find files

### ISSUE THREAD

**Issue by mmkolbe** [nv-nguyen/gigapose#22]
Hi Van and all.

I'm getting and error when I try to run the test below:

> # for 6D detection task
> python test.py test_dataset_name=hope run_id=$NAME_RUN test_setting=detection

I get this error:

> [...]
> [2024-09-30 15:01:15,251][src.custom_megapose.template_dataset][INFO] - Loaded 28 template datas
> dataset_name: (hope)
> det_model:cnos-sam
> det_model:cnos-sam
> Error executing job with overrides: ['test_dataset_name=hope', 'run_id=teste', 'test_setting=detection']
> Traceback (most recent call last):
>   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
>     return _target_(*args, **kwargs)
>   File "/home/marcel/gigapose/src/dataloader/test.py", line 94, in __init__
>     self.load_detections(test_setting=test_setting)
>   File "/home/marcel/gigapose/src/dataloader/test.py", line 108, in load_detections
>     self.test_list, self.cnos_dets = load_test_list_and_cnos_detections(
>   File "/home/marcel/gigapose/src/utils/inout.py", line 433, in load_test_list_and_cnos_detections
>     avail_det_files = os.listdir(cnos_dets_dir)
> FileNotFoundError: [Errno 2] No such file or directory: 'gigaPose_datasets/datasets/default_detections/core24_model_based_unseen/cnos-sam'

In fact this dataset part is not downloaded from the huggingface. And I saw you updated the repo a few days ago, with only cnos-fastsam data 
now:
[core24_model_based_unseen](https://huggingface.co/datasets/bop-benchmark/datasets/tree/main/default_detections/core24_model_based_unseen)

I tried to rename the folder and files, removing the 'fast' part', but I ran into another error.

In order to be able to reproduce the results, should I look for the folders 'cnos-sam' somewhere, or editing some part of the code?

**Comment by mmkolbe** [comment]
This error was solved by downloading manually the file in the Hugging Face, on previous commits, and putting in on the folder:
[...]gigapose/gigaPose_datasets/datasets/default_detections/core24_model_based_unseen/cnos-sam

The commit:
https://huggingface.co/datasets/bop-benchmark/datasets/tree/9c878d1404e9c9a77a7c81163cbe21a25841a9cb/default_detections/core24_model_based_unseen/cnos-sam

**Comment by fradif96** [comment]
Hello. I have the same problem. However I receive error 404 when clicking on the previous link. Do you know how to fix this?

**Comment by 39GodMissing** [comment]
Hello. I also have the same problem. However I receive error 404 when clicking on the previous link. Do you know how to fix this?

> This error was solved by downloading manually the file in the Hugging Face, on previous commits, and putting in on the folder: [...]gigapose/gigaPose_datasets/datasets/default_detections/core24_model_based_unseen/cnos-sam
> 
> The commit: https://huggingface.co/datasets/bop-benchmark/datasets/tree/9c878d1404e9c9a77a7c81163cbe21a25841a9cb/default_detections/core24_model_based_unseen/cnos-sam

**Comment by jinguangle** [comment]
@mmkolbe Hello. I also have the same problem. However I receive error 404 when clicking on the previous link. Do you know how to fix this?
