### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by CQUChenC** [nv-nguyen/gigapose#25]
Hello, thank you very much for your excellent work. 
**After I switched to the BOP2023 version (using the command git checkout 388e8bddd8a5443e284a7f70ad103d03f3f461c5), I started the program: python test.py test_dataset_name=lmo run_id=0, and received the following error:**
`Restoring states from the checkpoint path at ./gigaPose_datasets/pretrained/gigaPose_v1.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loaded model weights from checkpoint at ./gigaPose_datasets/pretrained/gigaPose_v1.ckpt
Testing DataLoader 0: 0%| | 0/200 [00:00<?,?it/s][2024-10-26 22:01:26,974][src.models.gigaPose][INFO] - Initializing template data...
100%|███████████████████████████████████████████████████████████████████████████████████| 8/8 [02:01<00:00, 15.14s/it]
[2024-10-26 22:03:28,125][src.models.gigaPose][INFO] - Init lmo done! Avg time=15.14378508925438 s/object0, 14.82s/it]
Error executing job with overrides: ['test_dataset_name=lmo', 'run_id=0']
Traceback (most recent call last):
File "/media/lls/ 新加卷 / CC_CODE/Code/gigapose_2023/gigapose/test.py", line 85, in <module>
run_test()
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
_run_hydra(
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
_run_app(
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
run_and_report(
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
raise ex
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
return func()
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
lambda: hydra.run (
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
_ = ret.return_value
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
raise self._return_value
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
ret.return_value = task_function (task_cfg)
File "/media/lls/ 新加卷 / CC_CODE/Code/gigapose_2023/gigapose/test.py", line 75, in run_test
trainer.test (
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 757, in test
return call._call_and_handle_interrupt (
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
return trainer.strategy.launcher.launch (trainer_fn, *args, trainer=trainer, **kwargs)
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 90, in launch
return function (*args, **kwargs)
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 806, in _test_impl
results = self._run (model, ckpt_path=self.ckpt_path)
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
results = self._run_stage ()
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1137, in _run_stage
return self._run_evaluate ()
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_evaluate
eval_loop_results = self._evaluation_loop.run ()
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
self.advance (*args, **kwargs)
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
dl_outputs = self.epoch_loop.run (self._data_fetcher, dl_max_batches, kwargs)
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
self.advance (*args, **kwargs)
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
output = self._evaluation_step (**kwargs)
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
output = self.trainer._call_strategy_hook (hook_name, *kwargs.values ())
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
output = fn (*args, **kwargs)
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 369, in test_step
return self.model.test_step (*args, **kwargs)
File "/home/lls/anaconda3/envs/gigapose/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func (*args, **kwargs)
File "/media/lls/ 新加卷 / CC_CODE/Code/gigapose_2023/gigapose/src/models/gigaPose.py", line 636, in test_step
self.eval_retrieval (
File "/media/lls/ 新加卷 / CC_CODE/Code/gigapose_2023/gigapose/src/models/gigaPose.py", line 518, in eval_retrieval
src_ae_features = template_data.ae_features [tar_label - 1]`
**IndexError: tensors used as indices must be long, byte or bool tensors.** 
Do you have any solutions to this problem?

**Comment by CQUChenC** [comment]
The problem has been solved. By adding tar_label = tar_label.long() before all occurrences of the error IndexError: tensors used as indices must be long, byte or bool tensors, the issue is resolved.
