### ISSUE TITLE
KeyError: 'fname' @ fname, value = filesample["fname"], filesample["data"]

### ISSUE THREAD

**Issue by mmkolbe** [nv-nguyen/gigapose#26]
Hello all.
Just ran into a error when trying to run the inference on single image for LMO dataset, by `python test.py test_dataset_name=lmoWonder3d run_id=run00001`

In the end I got this error on fname, on megapose part. Found no issue on this on the MegaPose repository as well.

Anyone got this too?

fname, value = filesample["fname"], filesample["data"]
[rank0]: KeyError: 'fname'

```
(gigapose) marcel@marcel-Aspire-GX-783:~/gigapose$ python test.py test_dataset_name=lmoWonder3d run_id=run00001
[2024-10-31 21:53:40,060][__main__][INFO] - Initializing logger, callbacks and trainer
[2024-10-31 21:53:40,063][__main__][INFO] - Tensorboard logger initialized at ./gigaPose_datasets/results/large_run00001/gigapose
ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[2024-10-31 21:53:40,131][__main__][INFO] - Trainer initialized!
Using cache found in /home/marcel/.cache/torch/hub/facebookresearch_dinov2_main
[2024-10-31 21:53:42,293][dinov2][INFO] - using MLP layer as FFN
[2024-10-31 21:53:49,710][src.models.network.ae_net][INFO] - Initialize AENet done!
[2024-10-31 21:53:49,864][src.models.network.ist_net][INFO] - Init for Regressor with done!
[2024-10-31 21:53:49,942][src.models.network.ist_net][INFO] - Init weights for ISTNet done!
[2024-10-31 21:53:49,942][src.models.network.ist_net][INFO] - Init for ISTNet done!
[2024-10-31 21:53:49,947][src.models.gigaPose][INFO] - Initialize GigaPose done!
[2024-10-31 21:53:49,947][__main__][INFO] - Model initialized!
[2024-10-31 21:53:50,201][src.dataloader.test][INFO] - Split: test for lmoWonder3d!
[2024-10-31 21:53:50,203][src.custom_megapose.web_scene_dataset][INFO] - WebSceneDataset: 1 shards
[2024-10-31 21:53:50,203][src.custom_megapose.web_scene_dataset][INFO] - IterableWebSceneDataset: 200 samples
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 6248.50it/s]
[2024-10-31 21:53:50,210][src.custom_megapose.template_dataset][INFO] - Loaded 8 template datas
1445it [00:00, 3755.33it/s]
[2024-10-31 21:53:51,148][src.utils.inout][INFO] - Detections: 1445 test samples!
[2024-10-31 21:53:51,168][src.dataloader.keypoints][INFO] - Initialized normalized center patch done!
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 12734.13it/s]
[2024-10-31 21:53:51,185][src.custom_megapose.template_dataset][INFO] - Loaded 8 template datas
[2024-10-31 21:53:51,186][__main__][INFO] - Dataloaders initialized!
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[W1031 21:53:51.924217400 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

You are using a CUDA device ('NVIDIA GeForce RTX 3060') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Restoring states from the checkpoint path at ./gigaPose_datasets/pretrained/gigaPose_v1.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loaded model weights from checkpoint at ./gigaPose_datasets/pretrained/gigaPose_v1.ckpt
Testing DataLoader 0:   0%|                                                                                                                                                        | 0/200 [00:00<?, ?it/s][2024-10-31 21:54:01,283][src.models.gigaPose][INFO] - Initializing template data ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [02:08<00:00, 16.11s/it]
[2024-10-31 21:56:10,139][src.models.gigaPose][INFO] - Init lmoWonder3d done! Avg time=16.10696342587471 s/object████████████████████████████████████████████████████████████| 8/8 [02:08<00:00, 15.54s/it]
Testing DataLoader 0: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 199/200 [15:40<00:04,  4.73s/it]Error executing job with overrides: ['test_dataset_name=lmoWonder3d', 'run_id=run00001']
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/marcel/gigapose/test.py", line 89, in <module>
[rank0]:     run_test()
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
[rank0]:     _run_hydra(
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
[rank0]:     _run_app(
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
[rank0]:     run_and_report(
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
[rank0]:     raise ex
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
[rank0]:     return func()
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
[rank0]:     lambda: hydra.run(
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
[rank0]:     _ = ret.return_value
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
[rank0]:     raise self._return_value
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
[rank0]:     ret.return_value = task_function(task_cfg)
[rank0]:   File "/home/marcel/gigapose/test.py", line 79, in run_test
[rank0]:     trainer.test(
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 785, in test
[rank0]:     return call._call_and_handle_interrupt(
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 834, in _test_impl
[rank0]:     results = self._run(model, ckpt_path=self.ckpt_path)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1179, in _run_stage
[rank0]:     return self._run_evaluate()
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1219, in _run_evaluate
[rank0]:     eval_loop_results = self._evaluation_loop.run()
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
[rank0]:     self.advance(*args, **kwargs)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
[rank0]:     dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
[rank0]:     self.advance(*args, **kwargs)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 121, in advance
[rank0]:     batch = next(data_fetcher)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
[rank0]:     return self.fetching_function()
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
[rank0]:     self._fetch_next_batch(self.dataloader_iter)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
[rank0]:     batch = next(iterator)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
[rank0]:     raise exception
[rank0]: KeyError: Caught KeyError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 33, in fetch
[rank0]:     data.append(next(self.dataset_iter))
[rank0]:   File "/home/marcel/anaconda3/envs/gigapose/lib/python3.9/site-packages/webdataset/pipeline.py", line 71, in iterator
[rank0]:     for sample in self.iterator1():
[rank0]:   File "/home/marcel/gigapose/src/custom_megapose/web_scene_dataset.py", line 204, in load_scene_ds_obs_iterator
[rank0]:     for sample in samples:
[rank0]:   File "/home/marcel/gigapose/src/megapose/utils/webdataset.py", line 39, in group_by_keys
[rank0]:     fname, value = filesample["fname"], filesample["data"]
[rank0]: KeyError: 'fname'

Testing DataLoader 0: 100%|█████████▉| 199/200 [15:41<00:04,  4.73s/it]                                                                                                                                    
[rank0]:[W1031 22:09:43.791693690 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())

```

**Comment by mmkolbe** [comment]
I just put the following and seems to be okay losing some shards data at this point, at least for testing the overall.
It refers to the file /gigapose/src/megapose/utils/webdataset.py
```
if "fname" not in filesample or "data" not in filesample:
    continue
```

```
# Handles duplicate file names in different shards
def group_by_keys(data, keys=base_plus_ext, lcase=True, suffixes=None, handler=None):
    """Return function over iterator that groups key, value pairs into samples.

    :param keys: function that splits the key into key and extension (base_plus_ext)
    :param lcase: convert suffixes to lower case (Default value = True)
    """
    current_sample = None
    for filesample in data:
        assert isinstance(filesample, dict)
        # check if filesample has fname and data keys
        if "fname" not in filesample or "data" not in filesample:
            continue
        fname, value = filesample["fname"], filesample["data"]
        prefix, suffix = keys(fname)
```
